"""add_timestamps_to_design

Revision ID: bd35b71dda2e
Revises: d277e32aad86
Create Date: 2026-02-21 17:56:14.164156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd35b71dda2e'
down_revision: Union[str, Sequence[str], None] = 'd277e32aad86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('designs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designs', 'updated_at')
    op.drop_column('designs', 'created_at')
    # ### end Alembic commands ###
