"""Add settings JSONB column to designs

Revision ID: ded1bd5e3d4f
Revises: bd35b71dda2e
Create Date: 2026-02-21 21:09:47.250286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ded1bd5e3d4f'
down_revision: Union[str, Sequence[str], None] = 'bd35b71dda2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designs', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designs', 'settings')
    # ### end Alembic commands ###
