"""add simulation export table

Revision ID: f066b8f6ff5b
Revises: 56d34d0896b1
Create Date: 2026-02-27 12:22:25.859469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f066b8f6ff5b'
down_revision: Union[str, Sequence[str], None] = '56d34d0896b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_exports_design_id'), 'simulation_exports', ['design_id'], unique=False)
    op.create_index(op.f('ix_simulation_exports_id'), 'simulation_exports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_exports_id'), table_name='simulation_exports')
    op.drop_index(op.f('ix_simulation_exports_design_id'), table_name='simulation_exports')
    op.drop_table('simulation_exports')
    # ### end Alembic commands ###
